### ISSUE TITLE
content creation

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/GitHub-Practice-For-All#102]
descriptions for about, for FAQ's etc can all be pulled from the main page read.me

https://github.com/RomchyFCC/GitHub-Practice-For-All/blob/master/README.md

to fill out the lorum parts of our landing page: https://romchyfcc.github.io/GitHub-Practice-For-All/

**Comment by lsurasani** [comment]
Hi, I'm new to open source, looking for my first contribution -- is this still open/if so can I take it?

**Comment by DarrenfJ** [comment]
@lsurasani yes definitely open! If you look at our main page here: https://romchyfcc.github.io/GitHub-Practice-For-All/

It's all still filler text. Any write-up that explains/supports the project would help..

More info is in the forum post (fCC forum). Will source a link if you are interested..

**Comment by lsurasani** [comment]
Sounds great! Link would be appreciated.

**Comment by DarrenfJ** [comment]
https://forum.freecodecamp.org/t/git-and-github-practice-for-all-us-noobies/171808

most of the history of the project..

**Comment by lsurasani** [comment]
Thanks! Any idea for what I should write for "Contact"?

**Comment by DarrenfJ** [comment]
hmm.. good point.. @RomchyFCC should we set up a generic gmail account and have that email available?

**Comment by RomchyFCC** [comment]
I think e-mail should be last resort, we have gitter, twitter and github, plenty of choices to choose from, what do you think?

**Comment by DarrenfJ** [comment]
Yah We could put our user names and say hit us up in the forum?

**Comment by lsurasani** [comment]
is that the fcc forum?

**Comment by RomchyFCC** [comment]
Thank you @lsurasani for resolving the issue!
