### ISSUE TITLE
Let's make a project 1 - Top slider

### ISSUE THREAD

**Issue by RomchyFCC** [RomchyFCC/GitHub-Practice-For-All#112]
Hey folks, sorry for the huge inactivity.
I won't go into to much detail so let's say, I've been busy at work and had some personal issues.

Anyway, here is our next project!!!!
We will copy [this webpage](https://victorhills.com/), the frontend part of it, so we can host it on github.
Use it as guidance if you'd like or try to hit the golfing theme in your design :)

We will split this into more parts and move on from there later on.

Your task here is to implement a slider at the top of the page, with random golf courses, 
**an image should slide automatically** 
**the edges can be clicked to see next or previous picture**
**there should be some hero text welcoming us to the site**

For more advanced and experienced developers, you may implement a video on one of the sliders!

**Comment by mills3** [comment]
Good to see you back Romchy, I'll have a go at this one

**Comment by RomchyFCC** [comment]
It's good to be back! Go ahead, thanks :)

**Comment by mills3** [comment]
Hey, can or should we push video files to Github? I just pushed an mp4 and webm file ( about 75mb ) and it took several minutes.

**Comment by mills3** [comment]
*UPDATE*  It seems that file limit is 100mb but will every fetch and push take minutes from now on?

**Comment by RomchyFCC** [comment]
Nah, just the first one, omce the file is the folder locally it will auto
be tracked and just moved, but great that you took that into consideration.
I'm excited to see what you created :)

**Comment by RomchyFCC** [comment]
This was done fast thanks to @mills3 it looks absolutely amazing!!!
