### ISSUE TITLE
Let's make a project 0 - Give me some space

### ISSUE THREAD

**Issue by RomchyFCC** [RomchyFCC/GitHub-Practice-For-All#113]
We are copying [this site](https://victorhills.com/), use it as guidance if you'd like or try to hit the golfing theme in your design :)

For this issues you should do the following:
  - create a folder with the name of the project in the root folder
  - put an empty script.js file inside the folder
  - put an empty style.css file inside the folder
  - put an index.html file inside the folder and connect it to all of the above

**Comment by h1tag** [comment]
I'll take this one.

**Comment by RomchyFCC** [comment]
Thank you @h1tag glad to see you're still with us :)

**Comment by DarrenfJ** [comment]
great work guys on keeping it alive!
