### ISSUE TITLE
Let's make a project 2 - What's on the menu

### ISSUE THREAD

**Issue by RomchyFCC** [RomchyFCC/GitHub-Practice-For-All#114]
We are copying [this site](https://victorhills.com/), use it as guidance if you'd like or try to hit the golfing theme in your design :)

For this issue you should do the following:
  - create a full-width menu with links to other pages
  - all links can be # except for the "home" link
  - home link should link back to the top of the main page
  - a logo should be added, you could use [this](https://logojoy.com) to create a logo for this group
  - ignore the cart image

Bonus:
  - add the social buttons that link back to this group project

**Comment by h1tag** [comment]
I'm not sure I can do all the requirements for this issue, but I'll try :)

**Comment by RomchyFCC** [comment]
Hey, sorry for the late reply, I was on vacation. Try your best, if it doesn't work out you can ask me to help you or anyone else really (people are so kind here :smile: ) or you can just submit the work you have done and I'll edit the issue for the next contributor.

**Comment by eribertt** [comment]
First timer here tld'r but how does this work?

**Comment by RomchyFCC** [comment]
Hey, how does what work?

**Comment by RomchyFCC** [comment]
Thanks @andirobinson for fixing this issue!
