### ISSUE TITLE
Add a Div style in the CSS

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/GitHub-Practice-For-All#24]
time to start redesigning the layout. 

I want to start by building out the divs and need to see what they look like on the page right now

add a div in the css like so:

```

div {

.....

}
```

and add borders to it. here is info on [borders](https://developer.mozilla.org/en-US/docs/Web/CSS/border)

**Comment by dmac0505** [comment]
I added some borders to the divs in the CSS file. I'm not sure what is considered 'claiming' the issue - perhaps this comment is considered 'claiming' it? :) Thanks.

**Comment by RomchyFCC** [comment]
this comment is indeed considered claiming the issue, it prevents 2 people working on the same issue in a team, it's good practice to let everyone know what you're up to :) thanks for claiming it!

**Comment by dmac0505** [comment]
Ok great thanks!
