### ISSUE TITLE
Change background on co-creator class to some gradient

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/GitHub-Practice-For-All#25]
need someone to go into the .co-creator class and add a gradient border there

we have a similar one in the body:

```
body {
	margin: 0;
	padding: 0;
	background: linear-gradient(90deg, purple, blue);
}
```

you decide on how you want it to go. [Info here](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient)

**Comment by bracar** [comment]
@DarrenfJ   This issue was taken and completed, thanks for the exercise
