### ISSUE TITLE
A bit of a challenge!

### ISSUE THREAD

**Issue by RomchyFCC** [RomchyFCC/GitHub-Practice-For-All#29]
I added a javascript file to our project and now we need someone to add a secret code to our program.

This can be done with a global event listener:
`window.addEventListener`

We listen for keys which we can save into a variable like an array.
`let secretArray = ['r', 'o', 'm', 'c', 'h', 'y']`

And when someone types the correct sequence of characters something magical can happen. (hint/idea already in the javascript file)

`if (myArray === secretArray) {play a secret sound or place a random image in the website}`

These array methods might come in handy: 
- .push
- .splice
- .join

Good luck & Happy coding!

**Comment by mills3** [comment]
I'll  do this, unless you want to leave it for people who haven't contributed yet?

**Comment by RomchyFCC** [comment]
Go ahead, we have easier issues as well for those who would like to contribute for the first time but don't want to write their names :)

**Comment by mills3** [comment]
Is it ok to make a pull request when my fork is 3 commits behind? ( forgot to fetch upstream before making changes  )

**Comment by mills3** [comment]
OK, I'm back in sync, i think :)

**Comment by RomchyFCC** [comment]
That's exactly why we have this, i'm glad you encountered this! When working in a team, you should always make sure you are on the most recent branch before starting your work, I'm happy you resolved it.
Well done on the challenge as well!
