### ISSUE TITLE
Add an image to spice things up!

### ISSUE THREAD

**Issue by RomchyFCC** [RomchyFCC/GitHub-Practice-For-All#30]
Let's try to spice things up with a simple picture.

The picture can be set up as a background in css:
`background: url('./img/cat.jpg')`

or in the html: 
`<img src="./img/cat.jpg">`

Your job is to find a random image which you like, make a new folder in our website folder and place that image there.
Ideally it would look something like this repofolder/The website/img/doggo.gif.

Once that is done, you can use the picture in our little website via 2 methods discussed above.

Please no NSFW content!

**Comment by h1tag** [comment]
Hey, is this still up for grabs? Because I see that someone already has added an image.

**Comment by RomchyFCC** [comment]
It is, that image was part of the secret code challenge :)

**Comment by RomchyFCC** [comment]
Issue resolved, thanks @h1tag

**Comment by h1tag** [comment]
@RomchyFCC can I change the background image again?
