### ISSUE TITLE
enhancements to div (padding and border styles)

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/GitHub-Practice-For-All#33]
recently I've been working on the [net ninja](https://www.thenetninja.co.uk/) material as part of [@P1xt](https://github.com/P1xt/p1xt-guides#summary) 'don't suck at CSS [challenge](https://medium.com/p1xts-blog/lets-make-november-suck-less-at-css-month-7fa7c80b5387)'

( youtube channel [here](https://www.youtube.com/channel/UCW5YeuERMmlnqo4oq8vwUpg) )

I'm at the part about [border styles](https://youtu.be/sdn5p4kf91c).

Can we add some [padding](https://developer.mozilla.org/en-US/docs/Web/CSS/padding) (20px should be good) to the div, and some size to the border, color, and maybe on of the fancier styles? ( border [schtuff](https://developer.mozilla.org/en-US/docs/Web/CSS/border) <-- there )

[the net ninja intro to CSS](https://www.youtube.com/watch?v=I9XRrlOOazo&list=PL4cUxeGkcC9gQeDH6xYhmO-db2mhoTSrT)

**Comment by h1tag** [comment]
I will give this a shot.

**Comment by RomchyFCC** [comment]
No problem, let's see what you make :)

**Comment by DarrenfJ** [comment]
thanks @h1tag, will close the issue out

**Comment by h1tag** [comment]
@RomchyFCC about the image: I was thinking about changing it, then changed my mind (but maybe I will still change it later). But thanks for the reply anyway.

I am still pretty much a beginner on Github, plus I haven't used it in a while, so these issues are giving me a good practice. Keep up the good work @RomchyFCC and @DarrenfJ . Thanks.
