### ISSUE TITLE
Projects set up for progress?

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/GitHub-Practice-For-All#4]
Did we want to use the GitHub built in project area to make up *fake* tasks so we have some sort of continuous progress to keep practicing with GitHub?

**Comment by RomchyFCC** [comment]
Didn't know that exists, we do want to use that yes. How can we set it up?

**Comment by DarrenfJ** [comment]
I took a quick look and it seems to act like a pared down trello board... 

but only you have the ability to create a project...

that said, I have forked the repo and can add stuff there and maybe do a PR for anything I add to a Project board?

This is all part of the fun of learning :D

**Comment by RomchyFCC** [comment]
Yea exactly what i was thinking. If this won't progress as needed we will quickly switch to a group project you talked about.

In the mean time I'll try to find more interested people to join.

I think the forks and PR's should work though (for now at least)

**Comment by DarrenfJ** [comment]
OK, will add a Project to mine and try to do a PR for that change to you

**Comment by DarrenfJ** [comment]
PR seems to only work for code changes.. I've made some issue changes and project additions but when i compare across forks no changes are logged.

**Comment by DarrenfJ** [comment]
"from what i've seen you only change on your end, when you create a pull
request, I get to look at it and merge if it's ok"

yes, that's the idea. that way I make a change and ask you to pull it into
the main repo

'though given you are also the contributor, I'm fairly certain you have
that power as well,'

I do now, yes. Found that out accidentally on last night first pull request
where I merged it from your repo end..

'you just need to connect to this repository via command line, but that
would ruin the whole git pull idea this project started with.'

I'm doing on my end via the desktop app. making changes in GutHub though
for now though...

'Do you use git pull to see if I made any changes and update your fork when
changes are made?'

yah, after I forked the repo you had make 2 changes and I pulled them back.
but I did it via the desktop app for GitHub so it acts a bit differently.
you do a sort of a 'reverse' Pull-request and pull the changes to your
fork...

**Comment by RomchyFCC** [comment]
Ok this issue has a great name, hopefully for now it is set up to progress, but obviously there might be more things to do. Right now we are banking on people to follow along with the forking and pull requesting but what if it doesn't stick, default back to the back and forth between us or does any other idea pop up?

**Comment by DarrenfJ** [comment]
Short term, while we build, we practice with GitHub..

Well long term would be a guide so people could pair-program, set up a
similar repo and do the same.. essentially creating a duplicate project to
propagate the tutourial.. and get git gitHub experience in the process...

Will try to map out what I mean a bit more...
