### ISSUE TITLE
Adding the first-timers-only 'friendly' badge to the main page read.me

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/GitHub-Practice-For-All#46]
please add the following [markdown](https://daringfireball.net/projects/markdown/syntax#philosophy) to the [read.me](https://github.com/RomchyFCC/GitHub-Practice-For-All/blob/master/README.md)

[![first-timers-only](http://img.shields.io/badge/first--timers--only-friendly-blue.svg?style=flat-square)](http://www.firsttimersonly.com/)

**Comment by DarrenfJ** [comment]
the code needed to do that is as follows:

`[![first-timers-only](http://img.shields.io/badge/first--timers--only-friendly-blue.svg?style=flat-square)](http://www.firsttimersonly.com/)`

**Comment by danielleshwed** [comment]
can I try this? :)

**Comment by RomchyFCC** [comment]
Thank you for handling the issue @danielleshwed
