### ISSUE TITLE
Change text color or text shadow

### ISSUE THREAD

**Issue by RomchyFCC** [RomchyFCC/GitHub-Practice-For-All#50]
The title sums it up well,
change the text color of the names that are poorly visible on our new background image.

How you target the text is up to you.
Possible choices include `* {}`, `body {}`, `p {}`, `a {}`.

How to change the text is up to you aswell, you could either use `text-shadow`, `color` or even `background-color` of the text.

Good luck!

**Comment by mills3** [comment]
I'll add some styles to Firuz Shoev to make it more visible, if nobody else wants it?

**Comment by RomchyFCC** [comment]
Nice, thanks!
I'll keep the issue up because we have one more name to fix.

**Comment by RomchyFCC** [comment]
This is now fixed, thanks @mills3 !
