### ISSUE TITLE
Contribute tips to our tips section and another newbie-friendly project

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/GitHub-Practice-For-All#51]
If you are posting git tips here, think about contributing also on the front-end-bible project

https://forum.freecodecamp.org/t/front-end-bible-contribute-on-github-and-learn/175660

https://github.com/JABedford/Front-End-Bible

**Comment by RomchyFCC** [comment]
Let me know if you are still up for moving the projects courses over to their repo
