### ISSUE TITLE
How could this repository be improved?

### ISSUE THREAD

**Issue by RomchyFCC** [RomchyFCC/GitHub-Practice-For-All#53]
First of all, I would like to thank all our contributors, with every contribution, you make this project infinitely better.
I would also like to thank @DarrenfJ, without his efforts to make this project as visible to the community as it is, I don't think we would get this far.

That being said, I want to know what are some of your thoughts on the project and how can we improve it?

I am striving to provide as real world team project as we can possibly make it. We are doing good on that part but we could be doing better I think.

I would love to read your thoughts, complaints, or issue ideas!

**Comment by DarrenfJ** [comment]
I'm always someone who is big on training. Part of my background is in that field.

I would like something akin to a base website that explains the concept, along with a guide custom made for adding you name.. something super _newbie_

website would be something like this: http://www.100daysofcode.com/

a base site where we launch people into the guides etc. Doesn't have to look like that but you get the idea.

Maybe the building of that site is something like a GitHub Community?

**Comment by GoddessMaat** [comment]
Thank you for your patience more details comming

**Comment by RomchyFCC** [comment]
I already made some changes, added a contributors list at the bottom of the readme and an in-file link to it at the top, also added a link to the page we have built so far so every one can see where we are at.
Refactored the to do list for contributing, would be awesome if someone else besides me tries it and let's me know if anything is missing or if they got stuck.

**Comment by DarrenfJ** [comment]
I can poke the forum again on it.. create an issue to test it out

**Comment by GoddessMaat** [comment]
I really wish this was simple im trying to install nodejs but yes please
keep helping me i have a meeting on Monday with a programmer hopefully
he'll help me with this

**Comment by RomchyFCC** [comment]
What exactly do you need help with @GoddessMaat ?
