### ISSUE TITLE
Need someone to test changes to the readme guide

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/GitHub-Practice-For-All#59]
this is from issue 53

https://github.com/RomchyFCC/GitHub-Practice-For-All/issues/53

"I already made some changes, added a contributors list at the bottom of the readme and an in-file link to it at the top, also added a link to the page we have built so far so every one can see where we are at.
_Refactored the to do list for contributing, would be awesome if someone else besides me tries it and let's me know if anything is missing or if they got stuck._" (italics added for emphasis)

Requires following the steps on the contributions readme and confirming that they make sense (which is essentially just adding your name to the webpage via a git PR)

https://github.com/RomchyFCC/GitHub-Practice-For-All/blob/master/README.md

**Comment by JChao7** [comment]
Looks good!

**Comment by h1tag** [comment]
I'm up for it.

**Comment by DarrenfJ** [comment]
@h1tag awesome, give it a go 
 
Thanks in advance

**Comment by h1tag** [comment]
@DarrenfJ is there changes in the steps (changed/added/removed steps)? Because I've already did some the steps in the guide (because I've contributed to this repo before), and I want to see if I have to redo some of the steps.

**Comment by RomchyFCC** [comment]
Yes, we made some changes to make it more descriptive and easier to follow(i hope). Great idea, we should make a section for those who have already made a PR

**Comment by RomchyFCC** [comment]
Ok, I think that's it. Thank you @h1tag for finding info holes and proposing the fixes!
