### ISSUE TITLE
Indent bullet points to more match numbers in rest of readme

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/GitHub-Practice-For-All#61]
from the read me ( https://github.com/RomchyFCC/GitHub-Practice-For-All/blob/master/README.md )

as seen in this screen shot. Bullet points need to be indented from the numbers:

![image](https://user-images.githubusercontent.com/13170765/37108104-2801f22e-2204-11e8-879e-511c7732f5d6.png)

**Comment by BIngZL1983** [comment]
correct me if I am wrong.  You want me to create a html file for this list, right?

**Comment by BIngZL1983** [comment]
Hi @Darrenfj

I have finished this issue. I will push my work tomorrow night. What I did was I created an un-ordered list, <ul></ul>, for those two bullet point within the second item in an ordered list, <ol></ol>. 

Hope that is something you are looking for. 
Thank you for this opportunity. :)

**Comment by RomchyFCC** [comment]
@BIngZL1983 The issue was already fixed by @heyAyushh, sorry I didn't respond sooner, I have been super busy. All we needed was another space, 1 space indentation was not enough. :)

**Comment by DarrenfJ** [comment]
@RomchyFCC @BIngZL1983  sorry missed it too got caught up in stuff last night..
