### ISSUE TITLE
JavaScript event listener

### ISSUE THREAD

**Issue by RomchyFCC** [RomchyFCC/GitHub-Practice-For-All#70]
Add an event listener to the sunshine.svg element which would make it disappear again after clicking it.

The sunshine element currently displays when a user click anywhere on the page but it is then stuck there.
use methods like `const img = document.querySelector('img')` or `document.getElementById('<img id>')` and then add an event listener like `img.addEventListener('click', function(){ })`

I realise this might be a more "advanced" project but feel free to try and do it anyway. You can ask me for more in-depth instructions on gitter @RomchyFCC or here. I'll reply ASAP.

EDIT: in the light of recent issues, this issue is still available but it is meant for the contributors.js.
More info here [74](https://github.com/RomchyFCC/GitHub-Practice-For-All/issues/74)

**Comment by h1tag** [comment]
I'll take this one! :smile:

**Comment by h1tag** [comment]
@RomchyFCC didn't notice you upvoted my comment. I was waiting for someone's approval to start. I'll start working on it ASAP.

**Comment by RomchyFCC** [comment]
@h1tag you don't need our permission :) and no worries, take your time, I'm excited to see how you make it

**Comment by h1tag** [comment]
@RomchyFCC 
> EDIT: in the light of recent issues, this issue is still available but it is meant for the contributors.js.
More info here 74

You mean I should work on issue #74 first, then on this one?

**Comment by RomchyFCC** [comment]
No, not at all, it just means you should work on contributors.js instead of
index.js

**Comment by h1tag** [comment]
@RomchyFCC but there's still no contributors.js file in this repo. So, I have to work on that issue first (I will have to create a contributors.js file ...), right?

**Comment by RomchyFCC** [comment]
Oh right, yes, in that case create a new file and i think thats it for that
issue so you can do both then

**Comment by RomchyFCC** [comment]
Thanks to @h1tag for resolving this issue!
