### ISSUE TITLE
Create a Container for a Nav Bar

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/GitHub-Practice-For-All#90]
Create a Container for a Nav Bar at the top of the page. I leave it up to you how to style it..

tips: https://css-tricks.com/navigation-in-lists-to-be-or-not-to-be/

for now leave this code alone as it links to our page with contributor names. later we will jazz it up..

```
<div class="contributors">
	<a href="./contributors.html">Contributors</a>
</div>
```

after the closing `</div>` you can add another div. 
Clone it off of the http://www.100daysofcode.com/ site

or at least add some tabs/buttons/links for 
About  Connect  Contact  FAQ  Resources

For now don't worry about the CSS too too much. but feel free to put a border around it so we can where it fits in with the page

**Comment by vignesh240** [comment]
I would like to do this @DarrenfJ

**Comment by DarrenfJ** [comment]
@vignesh240 consider it your!

**Comment by RomchyFCC** [comment]
Thank you @vignesh240 for resolving the issue
