### ISSUE TITLE
user should be able to link to parts of the page based off the nav bar

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/GitHub-Practice-For-All#93]
Nav bar has the following links:

Contributors - leave this one for now, it links to our contributor page
About
Connect
Contact
FAQ
Resources

Need to set up 'containers' on page for each of these sections.

One idea, do it as a <div> with a title as ID. Later we will build out each section with content. And add scrolling on the same page.

For now it can be an empty shell.. or user lorum ipsen text as filler ( https://lipsum.com/ )

It will need the section name as a header. (i,e, `<h1>`)

If you get stuck consider we are using this as a guide for cloning: http://100daysofcode.com/

But instead of having each link to a new page, we are putting content on one page and will use a scroll capability

**Comment by RomchyFCC** [comment]
Thanks for resolving the issue @OnlinePseudonym
