### ISSUE TITLE
users, when they navigate to the resources section, can link to resources

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/GitHub-Practice-For-All#95]
Nav bar on top of page can link to a container on the page that includes additional links to various resources

Resources should include: DevDocs, the sibling project (aka the Front End Bible), and the fCC library

dev docs url:
https://devdocs.io/

our sibling project's url:
https://github.com/JABedford/Front-End-Bible

fCC library url:
https://guide.freecodecamp.org/ 

don't worry too much about the CSS or style. for now build a container (`<div>`) that we can use to link to resources.

**Comment by chantellerobinson** [comment]
Hello, is this still an open issue please? If so, would it be possible for me to try tackle it? 

Many thanks.

**Comment by RomchyFCC** [comment]
Of course it's open, go for it! Thank you

**Comment by Zach048** [comment]
Hey!

New to open source, is this still open? I'd like to give it a shot.

**Comment by DarrenfJ** [comment]
You should be able to add something additional to the resources section..
the links suggested are places where additional documentation is included
for various technical topics..

**Comment by RomchyFCC** [comment]
Thanks for resolving this issue @Zach048 !
