### ISSUE TITLE
project drop-down menu

### ISSUE THREAD

**Issue by RomchyFCC** [RomchyFCC/GitHub-Practice-For-All#96]
We need a way to show off what we will build in the future.

Let's create a new navigation link (like contributors) that when clicked a dropdown menu appears with projects as links.

For now let's keep it simple:
navigation button name should be "Projects" and when clicked let's display an unordered list of projects, i.e.: `<ul><li><a href="#">project one</a></li><li><a href="#">project two</a></li></ul>`

I suggest using the click event in javascript to simply trigger `button.classList.toggle('hide')` which would toggle the class hide in css which could look something like:
`.hide {
  display: none;
}`
or
`.hide {
  visibility: hidden;
}`

This is merely a suggestion and the end code is up to you as long as it matches the goal of this issue.

I am available for more questions if needed.

**Comment by mGrossSRT** [comment]
Is it still an open issue? I could grab it by tonight if that's ok for you?

**Comment by DarrenfJ** [comment]
Yup, as far as I now @mGrossSRT , it's still outstanding!

Go for it!

D

**Comment by lsurasani** [comment]
Hi, is anyone still working on this issue? If not, I'd love to take a look!

**Comment by DarrenfJ** [comment]
@lsurasani there's been no action since @mGrossSRT asked to grab it...

@mGrossSRT are you still interested? If not @lsurasani can take it on..

**Comment by leesan11** [comment]
@DarrenfJ Hello! I am new to contributing. Would you mind if I try? I want try to make the code for it for practice. I don't mind if it isn't merged onto it. It's the practice that I really want!

**Comment by DarrenfJ** [comment]
Looks like it hasn't been touched yet.. so give it a go!

Also, feel free to add your name to the Contribution read.me but also the contributors page: https://romchyfcc.github.io/GitHub-Practice-For-All/contributors.html

**Comment by leesan11** [comment]
@DarrenfJ Thank you so much!

**Comment by RomchyFCC** [comment]
Thanks for resolving the issue @leesan11 !
