### ISSUE TITLE
user should be able to goto a section with instructions on how to add their name to the project.. and include a link to contributors page

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/GitHub-Practice-For-All#97]
user should be able to goto a section with instructions on how to add their name to the project.. and include a link to contributors page..

our main website is now going to be an intro page to the project

https://romchyfcc.github.io/GitHub-Practice-For-All/

it has a link in the top nav bar that takes you to the original project. The original project was a webpage that people added their name to and fancied it up. This was/is a simple page to allow someone to get their first Pull Request in on..

https://romchyfcc.github.io/GitHub-Practice-For-All/contributors.html

This issue is to have the link in the nav bar smooth scrool to a section that explains this (use lorum ipsem text for now).. with a link there to the contributors page.

## TL:DR ##

top nav bar has link to a contribution page. We want top link to goto a section on the page, and on that page an explanation how to contribute their name/first PR (we can handle the wording as a separate project)
and then link there to the contribution page...

---

### More info: ###

smooth scroolling was added in this PR:

https://github.com/RomchyFCC/GitHub-Practice-For-All/pull/94

you can see the detail of the changes here

https://github.com/RomchyFCC/GitHub-Practice-For-All/commit/ba90aff81645b3ef1b36720c2e613d34c29c76ce

Steps:

add a `<a href="#contributors">Contributors</a>` at top of the nav section.. replaces the existing one (move it to the section)

add a section.. 

```
<section id="contribtors">
	<h2>Contributors</h2>
	insert Lorem ipsum text 
</section>
```

this should go into the section now (link to contributors page)

```
<div class="contributors">
 <a href="./contributors.html">Contributors</a>
</div>
```

I'm not sure the contributors class is relevant anymore. Will have to double check this.

then of course do a separate PR for addition of your name to the contributors list!

**Comment by geekiam23** [comment]
Can I take a shot at it?

**Comment by DarrenfJ** [comment]
@geekiam23 definitely!

**Comment by RomchyFCC** [comment]
@geekiam23 thanks for resolving the issue
